export async function GET() {
  const URL =
    process.env.NEXT_PUBLIC_URL ||
    "https://bf86a94d-4eae-4e2b-a5d4-561fd4558851-00-13dju1adontpd.sisko.replit.dev/";

  const manifest = {
    ////
    accountAssociation: {
      header:
        "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4MTUyN0ZmMkEyNUNFZDU3YjJDMDE1RDdhRGJCNDU2OTQ5ODVGN2E3NiJ9",
      payload:
        "eyJkb21haW4iOiJiZjg2YTk0ZC00ZWFlLTRlMmItYTVkNC01NjFmZDQ1NTg4NTEtMDAtMTNkanUxYWRvbnRwZC5zaXNrby5yZXBsaXQuZGV2In0",
      signature:
        "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAC6XtDGqoxJA4-Bnlh-JjPEqfQooAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQM3gYRsnwyseq7ILo_4DCC5A3yabm5g45kAqBoOcpdxASJxblCAmdIuMMVVMdeDD-r6VFn-DV_q1wQMFOzAPgPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABznW8j0r-NbP1sO7uY0YavogOEE-Yp2Wbaz5rulFFYGdsLsWmtc-Db-xRWc1gVncq5n3yOUg8NHrgv-6z-bDLsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8FAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoibUFIQjh3c0ZSNVRZNTdrLVRuZ3U5NkFMaFQ1aDN5c1E1bDllWElHdUtBRSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS",
    },
    ////

    miniapp: {
      version: "1",
      name: "Adcoin",
      homeUrl: URL,
      iconUrl: `${URL}/creator-coin.jpg`,
      splashImageUrl: `${URL}/higher-coin.jpg`,
      splashBackgroundColor: "#000000",
      subtitle: "Connect Brands with Creators",
      description:
        "A mini app for managing advertising tokens and connecting advertisers with creators on Base.",
      screenshotUrls: [
        `${URL}/base-coin.jpg`,
        `${URL}/placeholder.jpg`,
        `${URL}/placeholder.jpg`,
      ],
      primaryCategory: "social",
      tags: ["adcoin", "advertising", "base", "creators", "brands"],
      tagline: "Tokenized Creator Advertising",
      ogTitle: "Adcoin - Mini App",
      ogDescription:
        "Connect advertisers and creators through on-chain advertising tokens.",
      ogImageUrl: `${URL}/placeholder.jpg`,
      noindex: true,
    },
  };

  return Response.json(manifest);
}
